#!/usr/bin/env -S GUILE_LOAD_PATH=${HOME}/.config/guix/current/share/guile/site/3.0/:${GUILE_LOAD_PATH} sudo -E guix repl -L ./ --
!#
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Copyright © 2023 Dmitry Klementiev

(use-modules
 (gnu system)
 (guix monads)
 (disko partitions vfat)
 (disko partitions btrfs)
 (disko device)
 (disko utils)
 (disko runner))

(define (install-operating-system os target)
  (let ((bootloader (operating-system-bootloader os))
	(bootcfg (operating-system-bootcfg os))
	(os-drv (operating-system-derivation os)))
    ((@@ (guix scripts system) install)
     os-drv target
     #:install-bootloader? #t
     #:bootloader bootloader
     #:bootcfg bootcfg)))

(run-disko
 (list
  (disko-device
   (file "/dev/nvme51qn23")
   (partitions
    (list
     (btrfs-partition
      (start (GiB 2))
      (end (percentage 100))
      (mount-point "/partition-root")
      (extra-args '("-f"))
      (subvolumes
       (list
	(btrfs-subvolume
	 (path "/rootfs")
	 (mount-point "/"))
	(btrfs-subvolume
	 (path "/home")
	 (mount-point "/home")
	 (options '("compress=zstd")))
	(btrfs-subvolume
	 (path "/gnu")
	 (mount-point "/gnu")
	 (options '("compress=zstd" "noatime")))
	(btrfs-subvolume
	 (path "/swap")
	 (mount-point "/.swapvol"))))
      (swapfiles
       (list
	(btrfs-swapfile
	 (path "/.swapvol/swapfile")
	 (size (GiB 8))))))
     (vfat-partition
      (start (MiB 1))
      (end (GiB 2))
      (mount-point "/boot/efi")))))))

;; Local Variables:
;; mode: scheme
;; End:
