(define-module (disko runner)
  #:use-module (disko device)
  #:use-module (disko partitions vfat)
  #:use-module (disko partitions btrfs)
  #:use-module (disko partitioning)
  #:use-module (disko file-systems)
  #:use-module (ice-9 pretty-print)
  #:export (run-disko))

(define (get-partition-start-end partition)
  (cond ((vfat-partition? partition)
	 (list (vfat-partition-start partition) (vfat-partition-end partition)))
	((btrfs-partition? partition)
	 (list (btrfs-partition-start partition) (btrfs-partition-end partition)))))

(define (run-disko devices)
  (for-each
   (lambda (i device)
     (part-disk (disko-device-file device)
		(disko-device-partitions device))
     (make-file-systems device)
     (newline))
   (iota (length devices)) devices)

  (pretty-print (devices->file-systems devices)))
